image:
  tag: v20260608-26b6300
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
rollout:
  autoPromotionEnabled: false
env:
  - name: S3_BUCKET
    value: "385551094956-us-east-1-data-source-production"
  - name: S3_KEY
    value: "data.csv"
  - name: AWS_REGION
    value: "us-east-1"
