apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/RaymonSun1230/my-devops-project.git
      targetRevision: dev
      path: helm-charts/frontend
      helm:
        valueFiles:
          - $values/gitops/dev/frontend/values.yaml
    - repoURL: https://github.com/RaymonSun1230/my-devops-project.git
      targetRevision: dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
