image:
  tag: v20260608-ca2903d
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
rollout:
  dynamicStableScale: true
  canarySteps:
    - setWeight: 25
    - pause: {}
    - setWeight: 100
  trafficRouting:
    alb:
      ingress: frontend
      servicePort: 7000
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/subnets: "subnet-09d2cbd4a54837f51,subnet-0b6114244852273a8"
env:
  - name: BACKEND_URL
    value: "http://backend-active:7001"
