{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  host: {{ include "frontend.fullname" . }}
  trafficPolicy:
    tls:
      mode: {{ .Values.istio.destinationRule.tlsMode | default "ISTIO_MUTUAL" }}
  subsets:
    - name: stable
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    - name: canary
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
{{- end }}
