replicaCount: 4
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 7000
  targetPort: 7000
rollout:
  enabled: true
  canaryMaxSurge: 1
  canaryMaxUnavailable: 0
  canarySteps:
    - setWeight: 10
    - pause:
        duration: 2m
    - setWeight: 50
    - pause:
        duration: 2m
    - setWeight: 100
    - pause:
        duration: 30s
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/subnets: ""
  hosts:
    - paths:
        - path: /
          pathType: Prefix
env:
  - name: BACKEND_URL
    value: "http://backend-active:7001"
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 128m
    memory: 128Mi
  limits:
    cpu: 256m
    memory: 256Mi
