replicaCount: 1
image:
  repository: 385551094956.dkr.ecr.us-east-1.amazonaws.com/app-backend
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 7001
  targetPort: 7001
  annotations: {}
serviceAccount:
  annotations: {}
rollout:
  enabled: true
  autoPromotionEnabled: false
  promotionDelaySeconds: 120
  scaleDownDelaySeconds: 30
env:
  - name: S3_BUCKET
    value: ""
  - name: S3_KEY
    value: "data.csv"
  - name: AWS_REGION
    value: "us-east-1"
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 128m
    memory: 128Mi
  limits:
    cpu: 256m
    memory: 256Mi
