image:
  tag: 059a604-20260605

istio:
  injection: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
rollout:
  autoPromotionEnabled: true

env:
  - name: S3_BUCKET
    value: "385551094956-us-east-1-data-source-staging"
  - name: S3_KEY
    value: "data.csv"
  - name: AWS_REGION
    value: "us-east-1"
