apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/RaymonSun1230/my-devops-project.git
      targetRevision: main
      path: helm-charts/backend
      helm:
        valueFiles:
          - $values/gitops/production/us-east-2/backend/values.yaml
    - repoURL: https://github.com/RaymonSun1230/my-devops-project.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  # syncPolicy disabled — manual sync only for production
