name: CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action"
        type: choice
        options:
          - deploy
          - rollback
        default: deploy
      environment:
        description: "Target Environment"
        type: choice
        options:
          - dev
          - test
          - staging
          - perf
          - production
        default: dev
      app:
        description: "Application"
        type: choice
        options:
          - backend
          - frontend
        default: backend
        
permissions:
  id-token: write
  contents: read

jobs:
  install:
    name: "Install — ${{ inputs.app }}"
    if: ${{ inputs.action == 'deploy' }}
    uses: ./.github/workflows/workflow-deploy-rollout.yaml
    with:
      action: install
      environment: ${{ inputs.environment }}
      app: ${{ inputs.app }}
    secrets: inherit

  promote:
    name: "Promote — ${{ inputs.app }}"
    if: ${{ inputs.action == 'deploy' }}
    needs: install
    uses: ./.github/workflows/workflow-deploy-rollout.yaml
    with:
      action: promote
      environment: ${{ inputs.environment }}
      app: ${{ inputs.app }}
    secrets: inherit

  rollback:
    name: "Rollback — ${{ inputs.app }}"
    if: ${{ inputs.action == 'rollback' }}
    uses: ./.github/workflows/workflow-deploy-rollout.yaml
    with:
      action: rollback
      environment: ${{ inputs.environment }}
      app: ${{ inputs.app }}
    secrets: inherit
